stages:
  - deploy

deploy:
  stage: deploy
  image: docker:stable-git
  script:
    - VERSION=`./git2version -s`
    - echo "${VERSION}"
    - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}
    - docker build . -t ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${VERSION}
    - docker tag ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${VERSION} ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${VERSION}
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${VERSION}
    - docker logout ${DOCKER_REGISTRY}

